In [1]:
import numpy as np

from cy_kaggle import cy_titanic

features, x_train, y = cy_titanic.load_dataset()

remove_features_index = [0, 2, 7, 9]
features = np.delete(features, remove_features_index, axis=0)
x_train = np.delete(x_train, remove_features_index, axis=1)

params = {'male': '1', 'female': '0', 'S': '0', 'Q': '1', 'C': '2'}
col_index = [1, -1]
fixed_missing_X = cy_titanic.fix_missing(x_train, col_index, params)

normDataSet, range_val, min_val = cy_titanic.auto_norm(fixed_missing_X)


In [8]:
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=2)
y = y.astype(float)
X_r2 = lda.fit(fixed_missing_X, y).transform(fixed_missing_X)

colors = ['navy', 'turquoise']
target_names = ['dead', 'alive']

# plt.figure()
# for color, i, target_name in zip(colors, [0, 1], target_names):
#     plt.scatter(X_r2[y == i, 0], X_r2[y == i, 1], alpha=.8, color=color,
#                 label=target_name)
# plt.legend(loc='best', shadow=False, scatterpoints=1)
# plt.title('LDA of titanic dataset')
# plt.show()


In [14]:
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=2)
y = y.astype(float)
X_r2 = lda.fit(fixed_missing_X, y).transform(fixed_missing_X)

colors = ['navy', 'turquoise']
target_names = ['dead', 'alive']

X_Zreo = np.zeros(X_r2.shape)

plt.figure()
for color, i, target_name in zip(colors, [0, 1], target_names):
    plt.scatter(X_r2[y == i], X_Zreo[y == i], alpha=.8, color=color,
                label=target_name)
plt.legend(loc='best', shadow=False, scatterpoints=1)
plt.title('LDA of titanic dataset')
plt.show()


In [16]:
from sklearn import svm
clf=svm.SVC()
clf.fit(fixed_missing_X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
predict_y = clf.predict(fixed_missing_X)


array([ 0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,
        1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [22]:
predict_y = clf.predict(fixed_missing_X)
sum_num = 0
error_num = 0
for y1, y2 in zip(y, predict_y):
    sum_num += 1
    if y1 != y2:
        error_num += 1
print("error rate is %f " % (error_num / sum_num))


error rate is 0.106622 


In [30]:
from imp import reload

reload(cy_titanic)
tuple_test= cy_titanic.load_testset()


FileNotFoundError: [Errno 2] No such file or directory: '/Users/nali/IdeaProjects/chengyPython/cy_kaggle/data/test.csv'

In [25]:
len(tuple_test)

3

In [26]:
tuple_test[0]

array(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='<U82')

In [27]:
tuple_test[2]

array(['0', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '1', '0',
       '0', '0', '1', '0', '1', '0', '1', '0', '1', '1', '1', '0', '1',
       '0', '0', '1', '0', '0', '1', '1', '0', '0', '0', '1', '0', '0',
       '1', '0', '0', '0', '1', '1', '0', '0', '1', '0', '0', '0', '0',
       '1', '1', '0', '1', '1', '0', '1', '0', '0', '1', '0', '0', '0',
       '1', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0',
       '1', '1', '0', '1', '1', '0', '1', '1', '0', '0', '1', '0', '0',
       '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0',
       '0', '0', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0',
       '0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '0', '1', '1',
       '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0

In [31]:
from imp import reload

reload(cy_titanic)
tuple_test= cy_titanic.load_testset()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nali/IdeaProjects/chengyPython/cy_kaggle/data/test.csv'

In [32]:
from imp import reload

reload(cy_titanic)

<module 'cy_kaggle.cy_titanic' from '/Users/nali/IdeaProjects/chengxiaoyPython/cy_kaggle/cy_titanic.py'>

In [33]:
tuple_test= cy_titanic.load_testset()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nali/IdeaProjects/chengyPython/cy_kaggle/data/test.csv'

In [34]:
from imp import reload

reload(cy_titanic)

<module 'cy_kaggle.cy_titanic' from '/Users/nali/IdeaProjects/chengxiaoyPython/cy_kaggle/cy_titanic.py'>

In [35]:
tuple_test= cy_titanic.load_testset()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nali/IdeaProjects/chengyPython/cy_kaggle/data/test.csv'

In [36]:
from imp import reload

reload(cy_titanic)

<module 'cy_kaggle.cy_titanic' from '/Users/nali/IdeaProjects/chengxiaoyPython/cy_kaggle/cy_titanic.py'>

In [39]:
test_features, test_set = cy_titanic.load_testset()
test_features

array(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='<U63')

In [40]:
remove_features_index = [0, 2, 7, 9]
test_features= np.delete(test_features, remove_features_index, axis=0)
t = np.delete(test_set, remove_features_index, axis=1)

params = {'male': '1', 'female': '0', 'S': '0', 'Q': '1', 'C': '2'}
col_index = [1, -1]
fixed_missing_X = cy_titanic.fix_missing(x_train, col_index, params)

In [ ]:
test_features
fixed_missing_test_X = cy_titanic.fix_missing(t, col_index, params)
fixed_missing_test_X
predict_y = clf.predict(fixed_missing_test_X)
predict_y
test_set

In [53]:
with open('cy_kaggle/data/svc_result.csv', 'w') as result_file:
    result_file.write("PassengerId,Survived" + "\n")
    for pid, flag in zip(test_set[:, 0], predict_y):
        result_file.write(pid + "," + str(int(flag)) + "\n")


In [55]:
from sklearn.datasets import load_iris # iris数据集
from sklearn.model_selection import train_test_split # 分割数据模块
from sklearn.neighbors import KNeighborsClassifier # K最近邻(kNN，k-NearestNeighbor)分类算法

#加载iris数据集
iris = load_iris()
X = iris.data
y = iris.target

#分割数据并
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)

#建立模型
knn = KNeighborsClassifier()

In [63]:
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

0.97368421052631582

In [68]:
features, x_train, y = cy_titanic.load_dataset()

remove_features_index = [0, 2, 7, 9]
features = np.delete(features, remove_features_index, axis=0)
x_train = np.delete(x_train, remove_features_index, axis=1)

params = {'male': '1', 'female': '0', 'S': '0', 'Q': '1', 'C': '2'}
col_index = [1, -1]
fixed_missing_X = cy_titanic.fix_missing(x_train, col_index, params)
y = y.astype(float)


In [73]:
from sklearn import svm
clf=svm.SVC()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

array([ 0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [91]:
X_train, X_test, y_train, y_test = train_test_split(fixed_missing_X, y,random_state=1)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)


0.70852017937219736

In [112]:
from sklearn import svm
clf=svm.SVC()
X_train, X_test, y_train, y_test = train_test_split(fixed_missing_X, y,random_state=1)

clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.67713004484304928

In [2]:
import numpy as np

from cy_kaggle import cy_titanic

features, x_train, y = cy_titanic.load_dataset()

remove_features_index = [0, 2, 7, 9]
features = np.delete(features, remove_features_index, axis=0)
x_train = np.delete(x_train, remove_features_index, axis=1)

params = {'male': '1', 'female': '0', 'S': '0', 'Q': '1', 'C': '2'}
col_index = [1, -1]
fixed_missing_X = cy_titanic.fix_missing(x_train, col_index, params)

normDataSet, range_val, min_val = cy_titanic.auto_norm(fixed_missing_X)

In [6]:
from sklearn import svm
from sklearn.model_selection import train_test_split # 分割数据模块
from sklearn.neighbors import KNeighborsClassifier # K最近邻(kNN，k-NearestNeighbor)分类算法

clf=svm.SVC()
X_train, X_test, y_train, y_test = train_test_split(fixed_missing_X, y,random_state=3)

clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.71300448430493268

In [7]:
knn=KNeighborsClassifier()
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.69955156950672648

In [42]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
yy = iris.target

#分割数据并
X_train, X_test, y_train, y_test = train_test_split(X, yy, random_state=4)
# clf=svm.LinearSVC()
# clf.fit(X_train,y_train)
# clf.score(X_test,y_test)
type(X_train)

numpy.ndarray

In [46]:
new_fix_X = np.delete(fixed_missing_X, [3, 4, 6], axis=1)
X_train, X_test, y_train, y_test = train_test_split(new_fix_X, y,random_state=3)
clf=svm.LinearSVC()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)
# X_train

0.66367713004484308

In [56]:
zeros = np.zeros((fixed_missing_X.shape[0], fixed_missing_X.shape[1] - 1))
print(zeros.shape)
#fixed_missing_X[:, 4] + fixed_missing_X[:, 3]
zeros[:,3]=fixed_missing_X[:, 4] + fixed_missing_X[:, 3]

(891, 6)


array([[ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])