In [40]:
import numpy as np
from cy_kaggle import cy_titanic


features, x_train, y = cy_titanic.load_dataset()

remove_features_index = [0, 2, 7, 9]
features = np.delete(features, remove_features_index, axis=0)
x_train = np.delete(x_train, remove_features_index, axis=1)


params = {'male': '1', 'female': '0', 'S': '0', 'Q': '1', 'C': '2'}
col_index = [1, -1]
fixed_missing_X = cy_titanic.fix_missing(x_train, col_index, params)

In [56]:
from imp import reload
reload(cy_titanic)
cy_titanic.auto_norm(fixed_missing_X)


[[ 1.          1.          0.27117366 ...,  0.          0.01415106  0.        ]
 [ 0.          0.          0.4722292  ...,  0.          0.13913574  1.        ]
 [ 1.          0.          0.32143755 ...,  0.          0.01546857  0.        ]
 ..., 
 [ 1.          0.          0.36792055 ...,  0.33333333  0.04577135  0.        ]
 [ 0.          1.          0.32143755 ...,  0.          0.0585561   1.        ]
 [ 1.          1.          0.39683338 ...,  0.          0.01512699  0.5       ]]
[   2.        1.       79.58      8.        6.      512.3292    2.    ]
[ 1.    0.    0.42  0.    0.    0.    0.  ]


(array([[ 1.        ,  1.        ,  0.27117366, ...,  0.        ,
          0.01415106,  0.        ],
        [ 0.        ,  0.        ,  0.4722292 , ...,  0.        ,
          0.13913574,  1.        ],
        [ 1.        ,  0.        ,  0.32143755, ...,  0.        ,
          0.01546857,  0.        ],
        ..., 
        [ 1.        ,  0.        ,  0.36792055, ...,  0.33333333,
          0.04577135,  0.        ],
        [ 0.        ,  1.        ,  0.32143755, ...,  0.        ,
          0.0585561 ,  1.        ],
        [ 1.        ,  1.        ,  0.39683338, ...,  0.        ,
          0.01512699,  0.5       ]]),
 array([   2.    ,    1.    ,   79.58  ,    8.    ,    6.    ,  512.3292,
           2.    ]),
 array([ 1.  ,  0.  ,  0.42,  0.  ,  0.  ,  0.  ,  0.  ]))