In [1]:
import numpy as np

from cy_kaggle import cy_titanic

features, x_train, y = cy_titanic.load_dataset()

remove_features_index = [0, 2, 7, 9]
features = np.delete(features, remove_features_index, axis=0)
x_train = np.delete(x_train, remove_features_index, axis=1)

params = {'male': '1', 'female': '0', 'S': '0', 'Q': '1', 'C': '2'}
col_index = [1, -1]
fixed_missing_X = cy_titanic.fix_missing(x_train, col_index, params)

normDataSet, range_val, min_val = cy_titanic.auto_norm(fixed_missing_X)


In [8]:
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=2)
y = y.astype(float)
X_r2 = lda.fit(fixed_missing_X, y).transform(fixed_missing_X)

colors = ['navy', 'turquoise']
target_names = ['dead', 'alive']

# plt.figure()
# for color, i, target_name in zip(colors, [0, 1], target_names):
#     plt.scatter(X_r2[y == i, 0], X_r2[y == i, 1], alpha=.8, color=color,
#                 label=target_name)
# plt.legend(loc='best', shadow=False, scatterpoints=1)
# plt.title('LDA of titanic dataset')
# plt.show()


In [14]:
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=2)
y = y.astype(float)
X_r2 = lda.fit(fixed_missing_X, y).transform(fixed_missing_X)

colors = ['navy', 'turquoise']
target_names = ['dead', 'alive']

X_Zreo = np.zeros(X_r2.shape)

plt.figure()
for color, i, target_name in zip(colors, [0, 1], target_names):
    plt.scatter(X_r2[y == i], X_Zreo[y == i], alpha=.8, color=color,
                label=target_name)
plt.legend(loc='best', shadow=False, scatterpoints=1)
plt.title('LDA of titanic dataset')
plt.show()


In [16]:
from sklearn import svm
clf=svm.SVC()
clf.fit(fixed_missing_X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
predict_y = clf.predict(fixed_missing_X)


array([ 0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,
        1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [22]:
predict_y = clf.predict(fixed_missing_X)
sum_num = 0
error_num = 0
for y1, y2 in zip(y, predict_y):
    sum_num += 1
    if y1 != y2:
        error_num += 1
print("error rate is %f " % (error_num / sum_num))


error rate is 0.106622 


In [30]:
from imp import reload

reload(cy_titanic)
tuple_test= cy_titanic.load_testset()


FileNotFoundError: [Errno 2] No such file or directory: '/Users/nali/IdeaProjects/chengyPython/cy_kaggle/data/test.csv'

In [25]:
len(tuple_test)

3

In [26]:
tuple_test[0]

array(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='<U82')

In [27]:
tuple_test[2]

array(['0', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '1', '0',
       '0', '0', '1', '0', '1', '0', '1', '0', '1', '1', '1', '0', '1',
       '0', '0', '1', '0', '0', '1', '1', '0', '0', '0', '1', '0', '0',
       '1', '0', '0', '0', '1', '1', '0', '0', '1', '0', '0', '0', '0',
       '1', '1', '0', '1', '1', '0', '1', '0', '0', '1', '0', '0', '0',
       '1', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0',
       '1', '1', '0', '1', '1', '0', '1', '1', '0', '0', '1', '0', '0',
       '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0',
       '0', '0', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0',
       '0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '0', '1', '1',
       '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0

In [31]:
from imp import reload

reload(cy_titanic)
tuple_test= cy_titanic.load_testset()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nali/IdeaProjects/chengyPython/cy_kaggle/data/test.csv'

In [32]:
from imp import reload

reload(cy_titanic)

<module 'cy_kaggle.cy_titanic' from '/Users/nali/IdeaProjects/chengxiaoyPython/cy_kaggle/cy_titanic.py'>

In [33]:
tuple_test= cy_titanic.load_testset()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nali/IdeaProjects/chengyPython/cy_kaggle/data/test.csv'

In [34]:
from imp import reload

reload(cy_titanic)

<module 'cy_kaggle.cy_titanic' from '/Users/nali/IdeaProjects/chengxiaoyPython/cy_kaggle/cy_titanic.py'>

In [35]:
tuple_test= cy_titanic.load_testset()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nali/IdeaProjects/chengyPython/cy_kaggle/data/test.csv'

In [36]:
from imp import reload

reload(cy_titanic)

<module 'cy_kaggle.cy_titanic' from '/Users/nali/IdeaProjects/chengxiaoyPython/cy_kaggle/cy_titanic.py'>

In [39]:
test_features, test_set = cy_titanic.load_testset()
test_features

array(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='<U63')

In [40]:
remove_features_index = [0, 2, 7, 9]
test_features= np.delete(test_features, remove_features_index, axis=0)
t = np.delete(test_set, remove_features_index, axis=1)

params = {'male': '1', 'female': '0', 'S': '0', 'Q': '1', 'C': '2'}
col_index = [1, -1]
fixed_missing_X = cy_titanic.fix_missing(x_train, col_index, params)

In [41]:
test_features

array(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'],
      dtype='<U63')

In [43]:
fixed_missing_test_X = cy_titanic.fix_missing(t, col_index, params)

In [44]:
fixed_missing_test_X

array([[  3.        ,   1.        ,  34.5       , ...,   0.        ,
          7.8292    ,   1.        ],
       [  3.        ,   0.        ,  47.        , ...,   0.        ,
          7.        ,   0.        ],
       [  2.        ,   1.        ,  62.        , ...,   0.        ,
          9.6875    ,   1.        ],
       ..., 
       [  3.        ,   1.        ,  38.5       , ...,   0.        ,
          7.25      ,   0.        ],
       [  3.        ,   1.        ,  30.27259036, ...,   0.        ,
          8.05      ,   0.        ],
       [  3.        ,   1.        ,  30.27259036, ...,   1.        ,
         22.3583    ,   2.        ]])

In [46]:
predict_y = clf.predict(fixed_missing_test_X)

In [47]:
predict_y

array([ 0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,
        1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
        1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,
        1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,
        0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,
        0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
        1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0

In [50]:
test_set

array([['892', '3', 'Kelly, Mr. James', ..., '7.8292', '', 'Q'],
       ['893', '3', 'Wilkes, Mrs. James (Ellen Needs)', ..., '7', '', 'S'],
       ['894', '2', 'Myles, Mr. Thomas Francis', ..., '9.6875', '', 'Q'],
       ..., 
       ['1307', '3', 'Saether, Mr. Simon Sivertsen', ..., '7.25', '', 'S'],
       ['1308', '3', 'Ware, Mr. Frederick', ..., '8.05', '', 'S'],
       ['1309', '3', 'Peter, Master. Michael J', ..., '22.3583', '', 'C']],
      dtype='<U63')

In [53]:
with open('cy_kaggle/data/svc_result.csv', 'w') as result_file:
    result_file.write("PassengerId,Survived" + "\n")
    for pid, flag in zip(test_set[:, 0], predict_y):
        result_file.write(pid + "," + str(int(flag)) + "\n")
