In [1]:
from sklearn import preprocessing
X = [[1., -1., 2.],
     [2., 0., 0.],
     [0., 1., -1.]]
X_normalized=preprocessing.normalize(X)


In [3]:
normalizer=preprocessing.Normalizer().fit(X)
normalizer.transform(X)

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [7]:
import numpy as np

rand_array = np.random.randint(1, 5, size=(3, 4))
print(rand_array)
min_vals = rand_array.min(0)
print(min_vals)
m = rand_array.shape[0]
print(rand_array-np.tile(min_vals, (m, 1)))

[[4 3 3 2]
 [4 4 2 2]
 [1 2 2 1]]
[1 2 2 1]
[[3 1 1 1]
 [3 2 0 1]
 [0 0 0 0]]
