In [1]:
import numpy as np

In [2]:
np.dot(100,40)

4000

In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
  
from sklearn import linear_model  
from sklearn import datasets  
  
diabetes = datasets.load_diabetes()  
X = diabetes.data  
y = diabetes.target  
  
print("Computing regularization path using the LARS ...")

Computing regularization path using the LARS ...


In [2]:
X.shape()

TypeError: 'tuple' object is not callable

In [3]:
type(X)

numpy.ndarray

In [4]:
X.shape

(442, 10)

In [5]:
y.shape

(442,)

In [6]:
alphas, _, coefs = linear_model.lars_path(X,y, method='Lasso',verbose=True)

.

In [7]:
coefs.shape

(10, 11)

In [8]:
type(coefs)

numpy.ndarray

In [9]:
coefs[1]

array([   0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,  -74.91651394, -111.97855446, -197.75650114,
       -226.13366183, -227.17579824, -239.81908937])

In [10]:
coefs

array([[   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,  -10.01219782],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,  -74.91651394, -111.97855446, -197.75650114,
        -226.13366183, -227.17579824, -239.81908937],
       [   0.        ,   60.11926965,  361.89461246,  434.75795962,
         505.65955847,  511.3480707 ,  512.04408899,  522.26484702,
         526.88546671,  526.39059435,  519.83978679],
       [   0.        ,    0.        ,    0.        ,   79.23644688,
         191.26988358,  234.15461616,  252.5270165 ,  297.15973689,
         314.38927158,  314.95046722,  324.39042769],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        , -103.94624877,
        -195.10582951, -237.34097312, -792.18416163],
       [   0.        ,    0.        ,    0.       

In [11]:
xx = np.sum(np.abs(coefs.T), axis=1)

In [12]:
coefs.T

array([[   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,   60.11926965,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,  361.89461246,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
         301.77534281,    0.        ],
       [   0.        ,    0.        ,  434.75795962,   79.23644688,
           0.        ,    0.        ,    0.        ,    0.        ,
         374.91583685,    0.        ],
       [   0.        ,    0.        ,  505.65955847,  191.26988358,
           0.        ,    0.        , -114.10097989,    0.        ,
         439.66494176,    0.        ],
       [   0.        ,  -74.91651394,  511.3480707 ,  234.15461616,
           0.        ,    0.        , -169.71139351,    0

In [13]:
xx

array([    0.        ,    60.11926965,   663.66995526,   888.91024335,
        1250.6953637 ,  1440.79804251,  1537.06598321,  1914.57052862,
        2115.73774356,  2195.55885543,  3460.00495515])

In [14]:
xx0 = np.sum(np.abs(coefs.T), axis=0)

In [17]:
xx0

array([   10.01219782,  1077.78011898,  4481.20425475,  2008.0778665 ,
        1328.57721302,   510.37411224,  1091.90503188,   394.79111081,
        4360.84372714,   263.56530732])

In [18]:
xx /= xx[-1]

In [19]:
xx

array([ 0.        ,  0.01737549,  0.19181185,  0.25691011,  0.36147213,
        0.41641502,  0.44423809,  0.55334329,  0.61148402,  0.63455367,  1.        ])

In [20]:
plt.plot(xx, coefs.T)  
ymin,ymax = plt.ylim()  
plt.vlines(xx,ymin,ymax,linestyle='dashed')  
plt.xlabel('|coef| / max|coef|')  
plt.ylabel('Coefficients')  
plt.title('LASSO Path')  
plt.axis('tight')  
plt.show() 

In [21]:
alphas

array([ 2.14804358,  2.01202713,  1.02466283,  0.71509967,  0.29441369,
        0.20086523,  0.15602991,  0.04520646,  0.01239247,  0.01151398,  0.        ])

In [22]:
_

[2, 8, 3, 6, 1, 9, 4, 7, 5, 0]

In [1]:
y_array = np.arange(1, 10, 2)


NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
y_array=np.arange(1,10,2)

In [4]:
import matplotlib.pyplot as plt

In [5]:
plt.plot(y_array,label='test')

In [6]:
plt.show()

In [7]:
plt.plot(y_array, color='lightgreen', linewidth=2, label='test')


In [10]:
plt.show()

In [11]:
plt.show()

In [12]:
y_array=np.arange(1,10)

In [13]:
y_array_new=np.arange(1,10,2)

In [14]:
plt.plot(y_array,color='lightgreen', linewidth=2, label='test1')
plt.plot(y_array_new,color='gold', linewidth=2,
         label='test2')

In [15]:
plt.show()

In [17]:
plt.legend(loc='best')
plt.show()

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_axes.py:545: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


In [18]:
plt.plot(y_array,color='lightgreen', linewidth=2, label='test1')
plt.plot(y_array_new,color='gold', linewidth=2,
         label='test2')
plt.legend(loc='best')
plt.show()

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import OrthogonalMatchingPursuit
from sklearn.linear_model import OrthogonalMatchingPursuitCV
from sklearn.datasets import make_sparse_coded_signal


In [2]:
n_components,n_features=512,100

In [3]:
n_nonzero_coefs=17

In [4]:
y, X, w = make_sparse_coded_signal(n_samples=1,
                                   n_components=n_components,
                                   n_features=n_features,
                                   n_nonzero_coefs=n_nonzero_coefs,
                                   random_state=0)

In [5]:
idx, = w.nonzero()

In [6]:
idx

array([ 46,  68,  76, 101, 123, 158, 195, 226, 227, 268, 269, 355, 359,
       399, 467, 492, 494])

In [7]:
w

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.09820563,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.43116899,  0.  

In [8]:
len(w)

512

In [9]:
type(w)

numpy.ndarray

In [10]:
type(X)

numpy.ndarray

In [11]:
X.shape

(100, 512)

In [12]:
len(y)

100

In [13]:
y_noisy = y + 0.05 * np.random.randn(len(y))

In [14]:
plt.figure(figsize=(7,7))

In [15]:
plt.subplot(4, 1, 1)
plt.xlim(0, 512)
plt.title("Sparse signal")
plt.stem(idx, w[idx])

<Container object of 3 artists>

In [16]:
omp=OrthogonalMatchingPursuit()

In [17]:
omp=OrthogonalMatchingPursuit(n_nonzero_coefs=n_nonzero_coefs)

In [18]:
omp.fit(X, y)
coef = omp.coef_
idx_r, = coef.nonzero()
plt.subplot(4, 1, 2)
plt.xlim(0, 512)
plt.title("Recovered signal from noise-free measurements")
plt.stem(idx_r, coef[idx_r])

<Container object of 3 artists>

In [19]:
omp.fit(X, y_noisy)
coef = omp.coef_
idx_r, = coef.nonzero()
plt.subplot(4, 1, 3)
plt.xlim(0, 512)
plt.title("Recovered signal from noisy measurements")
plt.stem(idx_r, coef[idx_r])

<Container object of 3 artists>

In [20]:
omp_cv = OrthogonalMatchingPursuitCV()
omp_cv.fit(X, y_noisy)
coef = omp_cv.coef_
idx_r, = coef.nonzero()
plt.subplot(4, 1, 4)
plt.xlim(0, 512)
plt.title("Recovered signal from noisy measurements with CV")
plt.stem(idx_r, coef[idx_r])

plt.subplots_adjust(0.06, 0.04, 0.94, 0.90, 0.20, 0.38)
plt.suptitle('Sparse signal recovery with Orthogonal Matching Pursuit',
             fontsize=16)
plt.show()

In [21]:
import numpy as np

In [22]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

from sklearn.linear_model import BayesianRidge, LinearRegression

# #############################################################################
# Generating simulated data with Gaussian weights
np.random.seed(0)
n_samples, n_features = 100, 100
X = np.random.randn(n_samples, n_features)  # Create Gaussian data
# Create weights with a precision lambda_ of 4.
lambda_ = 4.
w = np.zeros(n_features)

In [23]:
w

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
relevant_features = np.random.randint(0, n_features, 10)
for i in relevant_features:
    w[i] = stats.norm.rvs(loc=0, scale=1. / np.sqrt(lambda_))